# Generated by Django 3.0.8 on 2020-07-30 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import picklefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_id', models.IntegerField(blank=True, default=1)),
                ('full_name', models.CharField(max_length=100)),
                ('photo', models.ImageField(default='person/defaultPerson.jpg', upload_to='person/images')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default=None, max_length=1)),
                ('birth', models.CharField(blank=True, max_length=11)),
                ('death', models.CharField(blank=True, default='Alive', max_length=11)),
                ('same_vamsha', models.BooleanField(default=True)),
                ('batch_no', models.IntegerField(blank=True, default=0, verbose_name='Pusta Number')),
                ('profession', models.CharField(blank=True, max_length=50, null=True)),
                ('spouses', models.CharField(default='No Spouse', max_length=200)),
                ('children', picklefield.fields.PickledObjectField(blank=True, editable=False, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_edited_on', models.DateTimeField(auto_now=True)),
                ('father', models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'gender': 'M'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='person_father', to='backend.Person', verbose_name='Father')),
                ('last_edited_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('mother', models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'gender': 'F'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='person_mother', to='backend.Person', verbose_name='Mother')),
            ],
        ),
    ]
